services:
  bard:
    image: carnages/bard:latest
    container_name: bard
    restart: unless-stopped
    network_mode: host
    environment:
      DISCORD_TOKEN: "TOKEN"
    volumes:
      - bard_data:/data
      - /hosting:/hosting:ro
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  bard_data:
