services:
  bard:
    image: carnages/bard:latest
    container_name: bard
    restart: unless-stopped
    environment:
      DISCORD_TOKEN: "TOKEN"
    volumes:
      - bard_data:/data
      - /hosting:/hosting:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  bard_data:
